spring:
  application:
    name: bootspringdemo
  profiles:
    active:
     # - dev
      - druid
      - mybatis
      # - thymeleaf
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
debug: false